# A1

## A.1.3

In [1]:
import torch
torch.__version__

'2.2.2'

In [2]:
torch.cuda.is_available()

False

In [3]:
print(torch.backends.mps.is_available())

False


### Exercise A.1
Finished installing and setting up PyTorch on my computer.

### Exercise A.2
Finished running the supplementary code and everything outputed correctly. My environment is set up correctly.

# A2

## A.2.1

In [4]:
tensor0d = torch.tensor(1)
tensor1d = torch.tensor([1, 2, 3])
tensor2d = torch.tensor([[1, 2], [3, 4]])
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])


## A.2.2

In [5]:
tensor1d = torch.tensor([1, 2, 3])
print(tensor1d.dtype)

torch.int64


In [6]:
floatvec = torch.tensor([1.0, 2.0, 3.0])
print(floatvec.dtype)

torch.float32


In [7]:
floatvec = tensor1d.to(torch.float32)
print(floatvec.dtype)

torch.float32


## A.2.3

In [8]:
tensor2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(tensor2d)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [9]:
print(tensor2d.shape)
# 2 rows and 3 columns

torch.Size([2, 3])


In [10]:
print(tensor2d.reshape(3, 2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [11]:
print(tensor2d.view(3, 2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [12]:
print(tensor2d.T)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [13]:
print(tensor2d.matmul(tensor2d.T))

tensor([[14, 32],
        [32, 77]])


In [14]:
print(tensor2d @ tensor2d.T)

tensor([[14, 32],
        [32, 77]])


# A.3

In [15]:
import torch.nn.functional as F
y = torch.tensor([1.0])             # True label
x1 = torch.tensor([1.1])            # Input feature
w1 = torch.tensor([2.2])            # Weight parameter
b = torch.tensor([0.0])             # Bias unit
z = x1 * w1 + b                     # Net input
a = torch.sigmoid(z)                # Activation and output
loss = F.binary_cross_entropy(a, y)
print(f"The loss is {loss}.")

The loss is 0.0851878821849823.


# A.4

In [16]:
# Computing gradients via autograd
from torch.autograd import grad
y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2], requires_grad=True)
b = torch.tensor([0.0], requires_grad=True)

In [17]:
# Using grad function manually
z = x1 * w1 + b
a = torch.sigmoid(z)
loss = F.binary_cross_entropy(a, y)
grad_L_w1 = grad(loss, w1, retain_graph=True)
grad_L_b = grad(loss, b, retain_graph=True)
print(grad_L_w1)
print(grad_L_b)

(tensor([-0.0898]),)
(tensor([-0.0817]),)


In [18]:
# Automated process - PyTorch compute the gradients of all the leaf nodes in this graph.
loss.backward()
print(w1.grad)
print(b.grad)

tensor([-0.0898])
tensor([-0.0817])


# A.5

In [19]:
# A multilayer perceptron with two hidden layers
class NeuralNetwork(torch.nn.Module):
    def __init__(self, num_inputs, num_outputs):
        super().__init__()
        self.layers = torch.nn.Sequential(
            torch.nn.Linear(num_inputs, 30), # 1st hidden layer
            torch.nn.ReLU(),
            torch.nn.Linear(30, 20), # 2nd hidden layer
            torch.nn.ReLU(),
            torch.nn.Linear(20, num_outputs) # output layer
        )
    
    def forward(self, x):
        return self.layers(x)

In [20]:
model = NeuralNetwork(50, 3)
print(model)

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


In [21]:
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Total number of trainable model parameters: {num_params}")

Total number of trainable model parameters: 2213


In [22]:
print(model.layers[0].weight)
# Random output each time

Parameter containing:
tensor([[-0.0769, -0.1315, -0.0628,  ...,  0.0651, -0.0963,  0.0150],
        [ 0.1088,  0.1189, -0.0402,  ...,  0.0615, -0.1308,  0.0014],
        [-0.1208, -0.0530, -0.0950,  ..., -0.0507,  0.0258,  0.0428],
        ...,
        [-0.0443, -0.0705,  0.0420,  ...,  0.0346, -0.1325,  0.0888],
        [-0.1408, -0.1382, -0.0306,  ...,  0.0836,  0.0389, -0.1288],
        [ 0.0709, -0.0227,  0.0956,  ..., -0.0812, -0.0471, -0.0414]],
       requires_grad=True)


In [23]:
print(model.layers[0].weight.shape)

torch.Size([30, 50])


In [24]:
print(model.layers[0].bias)

Parameter containing:
tensor([-0.0136, -0.0625,  0.1190, -0.0049,  0.0259,  0.1228, -0.0907, -0.0212,
        -0.0369,  0.1031,  0.1312, -0.0463, -0.0832,  0.1355, -0.0222, -0.1207,
        -0.0162,  0.1072,  0.0653, -0.0971,  0.0010, -0.0565,  0.0242, -0.0051,
         0.0753,  0.0753, -0.1406, -0.0680, -0.0958, -0.1060],
       requires_grad=True)


In [25]:
print(model.layers[0].bias.shape)

torch.Size([30])


In [26]:
# Make the random number initialization reproducible
torch.manual_seed(123)
model = NeuralNetwork(50, 3)
print(model.layers[0].weight)

Parameter containing:
tensor([[-0.0577,  0.0047, -0.0702,  ...,  0.0222,  0.1260,  0.0865],
        [ 0.0502,  0.0307,  0.0333,  ...,  0.0951,  0.1134, -0.0297],
        [ 0.1077, -0.1108,  0.0122,  ...,  0.0108, -0.1049, -0.1063],
        ...,
        [-0.0787,  0.1259,  0.0803,  ...,  0.1218,  0.1303, -0.1351],
        [ 0.1359,  0.0175, -0.0673,  ...,  0.0674,  0.0676,  0.1058],
        [ 0.0790,  0.1343, -0.0293,  ...,  0.0344, -0.0971, -0.0509]],
       requires_grad=True)


In [27]:
# A forward pass
torch.manual_seed(123)
X = torch.rand((1, 50))
output = model(X)
print(output)

tensor([[-0.1262,  0.1080, -0.1792]], grad_fn=<AddmmBackward0>)


In [28]:
# For prediction after training
with torch.no_grad():
    output = model(X)
print(output)

tensor([[-0.1262,  0.1080, -0.1792]])


In [29]:
# Compute class-membership probabilities
with torch.no_grad():
    output = torch.softmax(model(X), dim=1)
print(output)

tensor([[0.3113, 0.3934, 0.2952]])


# A.6

In [30]:
# Creating a small toy dataset
X_train = torch.tensor([
    [-1.2, 3.1],
    [-0.9, 2.9],
    [-0.5, 2.6],
    [2.3, -1.1],
    [2.7, -1.5]
])
y_train = torch.tensor([0,0,0,1,1])
X_test = torch.tensor([
    [-0.8, 2.8],
    [2.6, -1.6]
])
y_test = torch.tensor([0,1])

In [31]:
# Defining a custom Dataset class
from torch.utils.data import Dataset
class ToyDataset(Dataset):
    def __init__(self, X, y):
        self.features = X
        self.labels = y
    
    def __getitem__(self, index):
        this_x = self.features[index]
        this_y = self.labels[index]
        return this_x, this_y
    
    def __len__(self):
        return self.labels.shape[0]

train_ds = ToyDataset(X_train, y_train)
test_ds = ToyDataset(X_test, y_test)
print(len(train_ds))

5


In [40]:
# Instantiating data loaders
from torch.utils.data import DataLoader
torch.manual_seed(0)

train_loader = DataLoader(
    dataset = train_ds,
    batch_size = 2,
    shuffle = True,
    num_workers = 0 # The number of background processes
)

test_loader = DataLoader(
    dataset = test_ds,
    batch_size = 2,
    shuffle = False,
    num_workers = 0
)

In [41]:
for idx, (x, y) in enumerate(train_loader):
    print(f'Batch {idx + 1}:', x, y)

Batch 1: tensor([[-0.9000,  2.9000],
        [ 2.7000, -1.5000]]) tensor([0, 1])
Batch 2: tensor([[-0.5000,  2.6000],
        [ 2.3000, -1.1000]]) tensor([0, 1])
Batch 3: tensor([[-1.2000,  3.1000]]) tensor([0])


In [42]:
# Drop the last batch
train_loader = DataLoader(
    dataset = train_ds,
    batch_size = 2,
    shuffle = True,
    num_workers = 0, # The number of background processes
    drop_last = True
)

In [43]:
for idx, (x, y) in enumerate(train_loader):
    print(f'Batch {idx + 1}:', x, y)

Batch 1: tensor([[-0.5000,  2.6000],
        [ 2.3000, -1.1000]]) tensor([0, 1])
Batch 2: tensor([[ 2.7000, -1.5000],
        [-1.2000,  3.1000]]) tensor([1, 0])
