# A1

## A.1.3

In [98]:
import torch
torch.__version__

'2.2.2'

In [99]:
torch.cuda.is_available()

False

In [100]:
print(torch.backends.mps.is_available())

False


### Exercise A.1
Finished installing and setting up PyTorch on my computer.

### Exercise A.2
Finished running the supplementary code and everything outputed correctly. My environment is set up correctly.

# A2

## A.2.1

In [101]:
tensor0d = torch.tensor(1)
tensor1d = torch.tensor([1, 2, 3])
tensor2d = torch.tensor([[1, 2], [3, 4]])
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])


## A.2.2

In [102]:
tensor1d = torch.tensor([1, 2, 3])
print(tensor1d.dtype)

torch.int64


In [103]:
floatvec = torch.tensor([1.0, 2.0, 3.0])
print(floatvec.dtype)

torch.float32


In [104]:
floatvec = tensor1d.to(torch.float32)
print(floatvec.dtype)

torch.float32


# A.2.3

In [105]:
tensor2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(tensor2d)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [106]:
print(tensor2d.shape)
# 2 rows and 3 columns

torch.Size([2, 3])


In [107]:
print(tensor2d.reshape(3, 2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [108]:
print(tensor2d.view(3, 2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [109]:
print(tensor2d.T)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [110]:
print(tensor2d.matmul(tensor2d.T))

tensor([[14, 32],
        [32, 77]])


In [111]:
print(tensor2d @ tensor2d.T)

tensor([[14, 32],
        [32, 77]])


# A.3

In [112]:
import torch.nn.functional as F

In [113]:
y = torch.tensor([1, 0], dtype=torch.float32)   # True label
x1 = torch.tensor([1, 1], dtype=torch.float32)  # Input feature
w1 = torch.tensor([2, 2], dtype=torch.float32)  # Weight parameter
b = torch.tensor([0, 0], dtype=torch.float32)   # Bias unit
z = x1 * w1 + b                                 # Net input
a = torch.sigmoid(z)                            # Activation and output
loss = F.binary_cross_entropy(a, y)
print(f"The loss is {loss}.")

The loss is 1.1269278526306152.
